id: 534eb683fa8744c0bf801aa7a738daf3
initial_creation_type: ocr
source_metadata:
  volumes:
    37ed4d37e41f4cb290788cdfaa0b78e1:
      base_file: v022.txt
      image_group_id: I1PD95867
      title: ''
      total_pages: 1409
      volume_number: 22
